#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model MicroreactorPK.Experiments.RunOneProfile
 Dymola Version 2025x, 2024-10-11 translated this at Mon Mar 30 17:11:47 2026

  Advanced.StoreProtectedVariables = true;
 */
#define DymolaStoreProtectedVariables_ 1

#include "matrixop.h"
#include "matrixop.c"
static int DymArraysV0[2]={0, 2};
/* Declaration of C-structs */
struct DymStruc0;
struct DymStruc0 {
  int  id_0member;
};
DYMOLA_STATIC struct DymStruc0 DymStruc0_construct(int   id_02) {
  struct DymStruc0 dummy_0;
  dummy_0.id_0member = id_02;
  return dummy_0;
}
/* Prototypes for functions used in model */
#include "ModelicaStandardTables.h"
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getNextTimeEvent_M(
  struct DymStruc0 tableID0_0, double  timeIn0_0);
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTimeTableTmax_M(
  struct DymStruc0 tableID0_0);
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTimeTableTmin_M(
  struct DymStruc0 tableID0_0);
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTimeTableValueNoDer2_M
  (struct DymStruc0 tableID0_0, int  icol0_0, double  timeIn0_0, double  
  nextTimeEvent0_0, double  prex_0nextTimeEvent);
DYMOLA_STATIC struct DymStruc0  Modelica_Blocks_Types_ExternalCombiTimeTable_M(
  const char*  tableName0_0, const char*  fileName0_0, RealArray   table0_0, 
  double  startTime0_0, IntegerArray   columns0_0, int  smoothness0_0, int  
  extrapolation0_0, double  shiftTime0_0, int  timeEvents0_0, int  
  verboseRead0_0, int id_, int alwaysMakeNew_);
DYMOLA_STATIC void Modelica_Blocks_Types_ExternalCombiTimeTable_destructor_M(
  void* externalCombiTimeTable0_0);
DYMOLA_STATIC int   Modelica_Utilities_Strings_isEmpty(const char*  string0_0);
/* Codes used in model */

/* Flattened Modelica model:

function Modelica.Blocks.Tables.Internal.getNextTimeEvent
discrete input Modelica.Blocks.Types.ExternalCombiTimeTable tableID;
discrete input Real timeIn "(Scaled) time value";
discrete output Real nextTimeEvent "(Scaled) next time event in table";

external "C" equation
nextTimeEvent = ModelicaStandardTables_CombiTimeTable_nextTimeEvent(tableID, timeIn) annotation(Include="#include \"ModelicaStandardTables.h\"", Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, IncludeDirectory="modelica://Modelica/Resources/C-Sources", LibraryDirectory="modelica://Modelica/Resources/Library");
end Modelica.Blocks.Tables.Internal.getNextTimeEvent;

  */
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getNextTimeEvent_M(
  struct DymStruc0 tableID0_0, double  timeIn0_0) {
  PushContext("Modelica.Blocks.Tables.Internal.getNextTimeEvent")
  {
    /* Declare outputs and temporaries */
    double   nextTimeEvent0_0;
    nextTimeEvent0_0=0;
    /* Start of real code */
    {
      nextTimeEvent0_0 = (ModelicaStandardTables_CombiTimeTable_nextTimeEvent)(
        externalTable_[tableID0_0.id_0member].obj_, timeIn0_0);
      }
    /* Output section */
    PopContext()
    return nextTimeEvent0_0;
  }}

/* Flattened Modelica model:

function Modelica.Blocks.Tables.Internal.getTimeTableTmax
discrete input Modelica.Blocks.Types.ExternalCombiTimeTable tableID;
discrete output Real timeMax "Maximum abscissa value in table";

external "C" equation
timeMax = ModelicaStandardTables_CombiTimeTable_maximumTime(tableID) annotation(Include="#include \"ModelicaStandardTables.h\"", Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, IncludeDirectory="modelica://Modelica/Resources/C-Sources", LibraryDirectory="modelica://Modelica/Resources/Library");
end Modelica.Blocks.Tables.Internal.getTimeTableTmax;

  */
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTimeTableTmax_M(
  struct DymStruc0 tableID0_0) {
  PushContext("Modelica.Blocks.Tables.Internal.getTimeTableTmax")
  {
    /* Declare outputs and temporaries */
    double   timeMax0_0;
    timeMax0_0=0;
    /* Start of real code */
    {
      timeMax0_0 = (ModelicaStandardTables_CombiTimeTable_maximumTime)(
        externalTable_[tableID0_0.id_0member].obj_);
      }
    /* Output section */
    PopContext()
    return timeMax0_0;
  }}

/* Flattened Modelica model:

function Modelica.Blocks.Tables.Internal.getTimeTableTmin
discrete input Modelica.Blocks.Types.ExternalCombiTimeTable tableID;
discrete output Real timeMin "Minimum abscissa value in table";

external "C" equation
timeMin = ModelicaStandardTables_CombiTimeTable_minimumTime(tableID) annotation(Include="#include \"ModelicaStandardTables.h\"", Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, IncludeDirectory="modelica://Modelica/Resources/C-Sources", LibraryDirectory="modelica://Modelica/Resources/Library");
end Modelica.Blocks.Tables.Internal.getTimeTableTmin;

  */
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTimeTableTmin_M(
  struct DymStruc0 tableID0_0) {
  PushContext("Modelica.Blocks.Tables.Internal.getTimeTableTmin")
  {
    /* Declare outputs and temporaries */
    double   timeMin0_0;
    timeMin0_0=0;
    /* Start of real code */
    {
      timeMin0_0 = (ModelicaStandardTables_CombiTimeTable_minimumTime)(
        externalTable_[tableID0_0.id_0member].obj_);
      }
    /* Output section */
    PopContext()
    return timeMin0_0;
  }}

/* Flattened Modelica model:

function Modelica.Blocks.Tables.Internal.getTimeTableValueNoDer2
discrete input Modelica.Blocks.Types.ExternalCombiTimeTable tableID;
input Integer icol "Column number";
discrete input Real timeIn "(Scaled) time value";
discrete input Real nextTimeEvent "(Scaled) next time event in table";
discrete input Real pre_nextTimeEvent "Pre-value of (scaled) next time event in table";
discrete output Real y "Interpolated value";

external "C" equation
y = ModelicaStandardTables_CombiTimeTable_getValue(tableID, icol, timeIn, nextTimeEvent, pre_nextTimeEvent) annotation(Include="#include \"ModelicaStandardTables.h\"", Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, IncludeDirectory="modelica://Modelica/Resources/C-Sources", LibraryDirectory="modelica://Modelica/Resources/Library");
annotation(derivative(noDerivative=nextTimeEvent, noDerivative=pre_nextTimeEvent)=Modelica.Blocks.Tables.Internal.getDerTimeTableValueNoDer);
end Modelica.Blocks.Tables.Internal.getTimeTableValueNoDer2;

  */
DYMOLA_STATIC double   Modelica_Blocks_Tables_Internal_getTimeTableValueNoDer2_M
  (struct DymStruc0 tableID0_0, int  icol0_0, double  timeIn0_0, double  
  nextTimeEvent0_0, double  prex_0nextTimeEvent) {
  PushContext("Modelica.Blocks.Tables.Internal.getTimeTableValueNoDer2")
  {
    /* Declare outputs and temporaries */
    double   y0_0;
    y0_0=0;
    /* Start of real code */
    {
      y0_0 = (ModelicaStandardTables_CombiTimeTable_getValue)(externalTable_[
        tableID0_0.id_0member].obj_, icol0_0, timeIn0_0, nextTimeEvent0_0, 
        prex_0nextTimeEvent);
      }
    /* Output section */
    PopContext()
    return y0_0;
  }}

/* Flattened Modelica model:

function constructor
input String tableName "Table name";
input String fileName "File name";
discrete input Real table[:, :];
discrete input Real startTime(unit = "s");
input Integer columns[:];
input Modelica.Blocks.Types.Smoothness smoothness;
input Modelica.Blocks.Types.Extrapolation extrapolation;
discrete input Real shiftTime(start = 0.0, unit = "s");
input Modelica.Blocks.Types.TimeEvents timeEvents(start = Modelica.Blocks.Types.TimeEvents.Always);
input Boolean verboseRead(start = true) "= true: Print info message; = false: No info message";
discrete output Modelica.Blocks.Types.ExternalCombiTimeTable externalCombiTimeTable;

external "C" equation
externalCombiTimeTable = ModelicaStandardTables_CombiTimeTable_init2(fileName, tableName, table, size(table, 1), size(table, 2), startTime, columns, size(columns, 1), smoothness, extrapolation, shiftTime, timeEvents, verboseRead) annotation(Include="#include \"ModelicaStandardTables.h\"", Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, IncludeDirectory="modelica://Modelica/Resources/C-Sources", LibraryDirectory="modelica://Modelica/Resources/Library");
end constructor;

  */
DYMOLA_STATIC struct DymStruc0  Modelica_Blocks_Types_ExternalCombiTimeTable_M(
  const char*  tableName0_0, const char*  fileName0_0, RealArray   table0_0, 
  double  startTime0_0, IntegerArray   columns0_0, int  smoothness0_0, int  
  extrapolation0_0, double  shiftTime0_0, int  timeEvents0_0, int  
  verboseRead0_0, int id_, int alwaysMakeNew_) {
  PushContext("Modelica.Blocks.Types.ExternalCombiTimeTable")
  {
    /* Declare outputs and temporaries */
    struct DymStruc0  externalCombiTimeTable0_0;
    externalCombiTimeTable0_0.id_0member=0;
    /* Start of real code */
    {
      externalCombiTimeTable0_0.id_0member=id_;
      if (externalTable_[id_].destructor_ && externalTable_[id_].obj_ && alwaysMakeNew_) {
      void*x_=externalTable_[id_].obj_;
      externalTable_[id_].obj_=0;
      (*(externalTable_[id_].destructor_))(x_);
      } else if (!externalTable_[id_].destructor_) {externalTable_[id_].obj_=0;}
      #if (defined(_OPENMP) && !defined(DISABLE_DYMOLA_OPENMP))
      if (!(externalTable_[id_].haveLock_)) {omp_init_lock(&(externalTable_[id_].lockExternal_));externalTable_[id_].haveLock_=1;}
      #endif
      externalTable_[id_].destructor_=Modelica_Blocks_Types_ExternalCombiTimeTable_destructor_M;

        if (!externalTable_[id_].obj_) externalTable_[id_].obj_ = (
        ModelicaStandardTables_CombiTimeTable_init2)(fileName0_0, tableName0_0, 
        table0_0.data, table0_0.dims[1-1], table0_0.dims[2-1], startTime0_0, 
        columns0_0.data, columns0_0.dims[1-1], smoothness0_0, extrapolation0_0, 
        shiftTime0_0, timeEvents0_0, verboseRead0_0);
      }
    /* Output section */
    PopContext()
    return externalCombiTimeTable0_0;
  }}

/* Flattened Modelica model:

function destructor
discrete input Modelica.Blocks.Types.ExternalCombiTimeTable externalCombiTimeTable;

external "C" equation
ModelicaStandardTables_CombiTimeTable_close(externalCombiTimeTable) annotation(Include="#include \"ModelicaStandardTables.h\"", Library={"ModelicaIO", "ModelicaMatIO", "ModelicaStandardTables", "zlib"}, IncludeDirectory="modelica://Modelica/Resources/C-Sources", LibraryDirectory="modelica://Modelica/Resources/Library");
end destructor;

  */
DYMOLA_STATIC void Modelica_Blocks_Types_ExternalCombiTimeTable_destructor_M(
  void* externalCombiTimeTable0_0) {
  PushContext("Modelica.Blocks.Types.ExternalCombiTimeTable.destructor")
  {
    /* Declare outputs and temporaries */
    /* Start of real code */
    {
      (ModelicaStandardTables_CombiTimeTable_close)(externalCombiTimeTable0_0);
      }
    /* Output section */
    PopContext()
    return ;
  }}

/* Flattened Modelica model:

function Modelica.Utilities.Strings.isEmpty
input String string;
output Boolean result "True, if string is empty";
protected 
Integer nextIndex;
Integer len;
public 
algorithm 
nextIndex := ModelicaStrings_skipWhiteSpace(string, 1);
len := ModelicaStrings_length(string);
if (len < 1 or nextIndex > len) then 
result := true;
else
result := false;
end if;
end Modelica.Utilities.Strings.isEmpty;

  */
DYMOLA_STATIC int   Modelica_Utilities_Strings_isEmpty(const char*  string0_0) {
  PushContext("Modelica.Utilities.Strings.isEmpty")
  {
    /* Declare outputs and temporaries */
    int   result0_0;
    int   nextIndex0_0;
    int   len0_0;
    MarkObject retmark_ = PushMark();
    result0_0=0;
    nextIndex0_0=0;
    len0_0=0;
    /* Start of real code */
      nextIndex0_0 = ModelicaStrings_skipWhiteSpace(string0_0, 1);
      len0_0 = ModelicaStrings_length(string0_0);
      if (len0_0 < 1 OR nextIndex0_0 > len0_0) {
        result0_0 = true;
      }
      else{
        result0_0 = false;
      }
    /* Output section */
    PopMark(retmark_);
    PopContext()
    return result0_0;
  }}
/* DSblock C-code: */

#define NX_    11
#define NX2_   0
#define NU_    0
#define NY_    27
#define NW_    55
#define NWP_   47
#define NP_    44
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   6
#define MAXAuxStrLen_   500
#define NHash1_ -2111289264
#define NHash2_ -759301253
#define NHash3_ 0
#define NI_    0
#define NRelF_ 1
#define NRel_  1
#define NTim_  1
#define NSamp_ 0
#define NCons_ 0
#define NA_    14
#define SizePre_ 2
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 2
#define NrDymolaTimers_ 0
#define NWhen_ 2
#define NCheckIf_ 0
#define NGlobalHelp_ 33
#define NGlobalHelpI_ 0
#define NSparse_ 0
#ifndef NExternalObject_
#define NExternalObject_ 1
#endif
#include "moutil.c"
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="MicroreactorPK.Experiments.RunOneProfile";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "C:/ProgramData/DassaultSystemes/Licenses/DSLicSrv.txt";
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[23]={9 , 2 , 1 , 11 , 2 , 2 , 10 , 1 , 3 , 1 , 4
   , 1 , 5 , 1 , 6 , 1 , 7 , 1 , 8 , 1 , 9 , 0 , 0};
static int QJacobianGrp0[12]={1, 1, 1, 1, 1, 1, 1, 1, 1, 11, 11, 0};
static int QJacobianGrp1[11]={2, 2 , 2 , 1 , 2 , 10 , 3 , 9 , 10 , 11 , 0};
static int QJacobianGrp2[6]={1, 3 , 2 , 1 , 3 , 0};
static int QJacobianGrp3[6]={1, 4 , 2 , 1 , 4 , 0};
static int QJacobianGrp4[6]={1, 5 , 2 , 1 , 5 , 0};
static int QJacobianGrp5[6]={1, 6 , 2 , 1 , 6 , 0};
static int QJacobianGrp6[6]={1, 7 , 2 , 1 , 7 , 0};
static int QJacobianGrp7[7]={1, 8 , 3 , 1 , 8 , 9 , 0};
static int QJacobianGrp8[8]={1, 9 , 4 , 1 , 8 , 9 , 10 , 0};
DYMOLA_STATIC struct QJacobianTag_ QJacobianGC2_[10]={
{0, QJacobianGrp0},{1, QJacobianGrp1},{1, QJacobianGrp2},{1, QJacobianGrp3},{1, 
  QJacobianGrp4},{1, QJacobianGrp5},{1, QJacobianGrp6},{1, QJacobianGrp7},{1, 
  QJacobianGrp8},{0,0}};
DYMOLA_STATIC double QJacobianCD_[12]={0  , 44 , 50 , 54 , 56 , 56 , 54 , 50 , 44
   , 36 , 130 , 154};
#include "dsblock1.c"

/* Define variable names. */

#define Sections_

TranslatedEquations
InitialSection
#if defined(DynSimStruct)
DYNX(W_,47) = 0;
DYNX(W_,48) = 0;
DYNX(Y_,15) = 1.0;
#endif

InitialSection
#if defined(DynSimStruct)
DYNX(W_,3) = 3;
DYNX(W_,21) = 6;
#endif
DYNSetAuxString(did_, "generated_profiles/root_002__profile_000000__full.mat", 0);
DYNSetAuxString(did_, "profile", 1);
DYNSetAuxString(did_, "generated_profiles/root_002__profile_000000__full.mat", 2);
DYNSetAuxString(did_, "profile", 3);
DYNSetAuxString(did_, "profile", 4);
DYNSetAuxString(did_, "generated_profiles/root_002__profile_000000__full.mat", 5);
#if defined(DynSimStruct)
DYNX(W_,10) = 1;
DYNX(W_,4) = true;
DYNX(W_,8) = 1;
DYNX(W_,9) = 1;
DYNX(W_,12) = false;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(W_,0) = DYNX(DP_,0);
DYNX(W_,1) = DYNX(DP_,1);
DYNX(W_,2) = DYNX(DP_,2);
DYNX(W_,5) = DYNX(W_,0);
DYNX(W_,6) = DYNX(W_,1);
DYNX(W_,7) = DYNX(W_,2);
DYNX(W_,11) = DYNX(DP_,5);
InitialBoundSection

/* Introducing 2 common subexpressions whereof 2 are global used in 1
   expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 1
   are booleans. */
DYNX(DYNhelp,0) = (PushModelContext(1,"Modelica.Utilities.Strings.isEmpty(prof.tab.fileName)")
  Modelica_Utilities_Strings_isEmpty("generated_profiles/root_002__profile_000000__full.mat"));
PopModelContext();
DYNX(DYNhelp,1) = divinvGuarded(DYNX(W_,10),"prof.tab.timeScale");
{
  struct DymStruc0 dummy_DymStruc0;
  dummy_DymStruc0 = (PushModelContext(1,"Modelica.Blocks.Types.ExternalCombiTimeTable((if prof.tab.tableOnFile then prof.tab.tableName else \"NoName\"), (if prof.tab.tableOnFile and prof.tab.fileName <> \"NoName\" and  not Modelica.Utilities.Strings.isEmpty(prof.tab.fileName) then prof.tab.fileName else \"NoName\"), prof.tab.table, prof.tab.startTime/prof.tab.timeScale, prof.tab.columns, prof.tab.smoothness, prof.tab.extrapolation, prof.tab...")
    Modelica_Blocks_Types_ExternalCombiTimeTable_M(IF DYNX(W_,4) THEN "profile"
     ELSE "NoName", IF DYNX(W_,4) AND (strcmp("generated_profiles/root_002__profile_000000__full.mat",
     "NoName")!=0) AND  NOT DYNX(DYNhelp,0) THEN "generated_profiles/root_002__profile_000000__full.mat"
     ELSE "NoName", RealTemporaryDense2( (Real*)(0), 2, DymArraysV0), 
    DYNX(DYNhelp,1)*DYNX(DP_,5), IntegerTemporaryDense( &DYNX(W_,5), 1, 3), 
    (Integer)(DYNX(W_,8)), (Integer)(DYNX(W_,9)), DYNX(DYNhelp,1)*DYNX(W_,11), 
    (Integer)(IF DYNX(W_,8) == 1 THEN DYNX(DP_,6) ELSE IF DYNX(W_,8) == 3 THEN 1
     ELSE 3), (Integer)(IF DYNX(W_,4) THEN DYNX(DP_,3) ELSE false), 0, 1));
  DYNX(W_,20) = dummy_DymStruc0.id_0member;
PopAllMarks();
}
BoundParameterSection

/* Introducing 0 common subexpressions and reusing 1 variables totally whereof 1
   are global used in 0 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(W_,15) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableTmin(\nprof.tab.tableID)")
  Modelica_Blocks_Tables_Internal_getTimeTableTmin_M(DymStruc0_construct(
  (Integer)(DYNX(W_,20)))));
PopModelContext();
DYNX(W_,13) = DYNX(W_,15)*DYNX(W_,10);

/* Introducing 0 common subexpressions and reusing 1 variables totally whereof 1
   are global used in 0 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(W_,16) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableTmax(\nprof.tab.tableID)")
  Modelica_Blocks_Tables_Internal_getTimeTableTmax_M(DymStruc0_construct(
  (Integer)(DYNX(W_,20)))));
PopModelContext();
DYNX(W_,14) = DYNX(W_,16)*DYNX(W_,10);
DYNX(W_,17) = DYNX(DP_,4);
DYNX(W_,18) = DYNX(DP_,4);
DYNX(W_,19) = DYNX(DP_,4);
DYNX(W_,22) = DYNX(DP_,14)+DYNX(DP_,15)+DYNX(DP_,16)+DYNX(DP_,17)+DYNX(DP_,18)+
  DYNX(DP_,19);
DYNX(W_,23) = divGuarded(DYNX(DP_,14),"reactor.betas[1]",DYNX(DP_,7)*DYNX(DP_,8),
  "reactor.Lambda*reactor.lambdas[1]");
DYNX(W_,24) = divGuarded(DYNX(DP_,15),"reactor.betas[2]",DYNX(DP_,7)*DYNX(DP_,9),
  "reactor.Lambda*reactor.lambdas[2]");
DYNX(W_,25) = divGuarded(DYNX(DP_,16),"reactor.betas[3]",DYNX(DP_,7)*
  DYNX(DP_,10),"reactor.Lambda*reactor.lambdas[3]");
DYNX(W_,26) = divGuarded(DYNX(DP_,17),"reactor.betas[4]",DYNX(DP_,7)*
  DYNX(DP_,11),"reactor.Lambda*reactor.lambdas[4]");
DYNX(W_,27) = divGuarded(DYNX(DP_,18),"reactor.betas[5]",DYNX(DP_,7)*
  DYNX(DP_,12),"reactor.Lambda*reactor.lambdas[5]");
DYNX(W_,28) = divGuarded(DYNX(DP_,19),"reactor.betas[6]",DYNX(DP_,7)*
  DYNX(DP_,13),"reactor.Lambda*reactor.lambdas[6]");
DYNX(W_,29) = 0.5*(DYNX(DP_,25)+DYNX(DP_,26));
DYNX(W_,30) = divGuarded(DYNX(DP_,20),"reactor.P_r",DYNX(DP_,36)*(DYNX(DP_,26)-
  DYNX(DP_,25)),"reactor.cp_N2*(reactor.TN_out-reactor.TN_in)");
DYNX(W_,31) = DYNX(W_,30)*DYNX(DP_,37);

/* Introducing 2 common subexpressions whereof 2 are global used in 1
   expressions */
/* Of the common subexpressions 2 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,2) = fabs(DYNX(DP_,22)-DYNX(DP_,23));
DYNX(DYNhelp,3) = divinvGuarded(DYNX(DYNhelp,2),"abs(reactor.Tf0-reactor.Tm0)");
DYNX(W_,32) = DYNX(DYNhelp,3)*DYNX(DP_,21)*DYNX(DP_,20);

/* Introducing 2 common subexpressions whereof 2 are global used in 1
   expressions */
/* Of the common subexpressions 2 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,4) = fabs(DYNX(DP_,23)-DYNX(DP_,24));
DYNX(DYNhelp,5) = divinvGuarded(DYNX(DYNhelp,4),"abs(reactor.Tm0-reactor.Thp0)");
DYNX(W_,33) = DYNX(DYNhelp,5)*DYNX(DP_,20);

/* Introducing 2 common subexpressions whereof 2 are global used in 1
   expressions */
/* Of the common subexpressions 2 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,6) = fabs(DYNX(DP_,24)-DYNX(W_,29));
DYNX(DYNhelp,7) = divinvGuarded(DYNX(DYNhelp,6),"abs(reactor.Thp0-reactor.TN0)");
DYNX(W_,34) = DYNX(DYNhelp,7)*DYNX(DP_,20);

/* Introducing 2 common subexpressions whereof 2 are global used in 1
   expressions */
/* Of the common subexpressions 2 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,8) = fabs(DYNX(W_,29)-DYNX(DP_,27));
DYNX(DYNhelp,9) = divinvGuarded(DYNX(DYNhelp,8),"abs(reactor.TN0-reactor.Tsg0)");
DYNX(W_,35) = DYNX(DYNhelp,9)*DYNX(DP_,20);
DYNX(DYNhelp,10) = divinvGuarded(DYNX(W_,32),"reactor.G_f_g");
DYNX(W_,36) = DYNX(DYNhelp,10)*DYNX(DP_,30)*DYNX(DP_,31);
DYNX(W_,37) = DYNX(DYNhelp,10)*DYNX(DP_,32)*DYNX(DP_,33);
DYNX(DYNhelp,11) = divinvGuarded(DYNX(W_,33),"reactor.G_g_hp");
DYNX(W_,38) = DYNX(DYNhelp,11)*DYNX(DP_,32)*DYNX(DP_,33);
DYNX(W_,39) = DYNX(DYNhelp,11)*DYNX(DP_,34)*DYNX(DP_,35);
DYNX(DYNhelp,12) = divinvGuarded(DYNX(W_,34),"reactor.G_hp_N2");
DYNX(W_,40) = DYNX(DYNhelp,12)*DYNX(DP_,34)*DYNX(DP_,35);
DYNX(W_,41) = DYNX(DYNhelp,12)*DYNX(W_,31)*DYNX(DP_,36);
DYNX(DYNhelp,13) = divinvGuarded(DYNX(W_,35),"reactor.G_N2_sg");
DYNX(W_,42) = DYNX(DYNhelp,13)*DYNX(W_,31)*DYNX(DP_,36);
DYNX(W_,43) = divinvGuarded(DYNX(DP_,30)*DYNX(DP_,31),"reactor.M_f*reactor.cp_f");
DYNX(DYNhelp,14) = divinvGuarded(DYNX(DP_,41),"reactor.n_drums");
DYNX(W_,44) = DYNX(DYNhelp,14)*DYNX(DP_,42)*1E-05;

/* Introducing 1 common subexpressions whereof 1 are global used in 0
   expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,15) = cos(0.017453292519943295*DYNX(DP_,43));
DYNX(W_,45) = 0.5*DYNX(W_,44)*(1.0-DYNX(DYNhelp,15));
DYNX(W_,46) = DYNX(DP_,41)*DYNX(W_,45);
InitialSection
InitialStartSection
InitialStartSection2
DYNX(X_,1) = DYNX(W_,23);
DYNX(X_,2) = DYNX(W_,24);
DYNX(X_,3) = DYNX(W_,25);
DYNX(X_,4) = DYNX(W_,26);
DYNX(X_,5) = DYNX(W_,27);
DYNX(X_,6) = DYNX(W_,28);
DYNX(X_,7) = DYNX(DP_,22);
DYNX(X_,8) = DYNX(DP_,23);
DYNX(X_,9) = DYNX(DP_,24);
DYNX(X_,10) = DYNX(W_,29);
DYNX(Y_,1) = DYNX(W_,29);
DYNX(Y_,2) = DYNX(DP_,23);
DYNX(Y_,3) = DYNX(DP_,24);
DYNX(Y_,4) = DYNX(DP_,22);
DYNX(Y_,9) = DYNX(W_,23);
DYNX(Y_,10) = DYNX(W_,24);
DYNX(Y_,11) = DYNX(W_,25);
DYNX(Y_,12) = DYNX(W_,26);
DYNX(Y_,13) = DYNX(W_,27);
DYNX(Y_,14) = DYNX(W_,28);
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialBoundSection
DYNX(Aux_,1) = DYNX(W_,48);
DYNX(Aux_,0) = DYNX(W_,47);
InitialSection
InitialSection2
DYNX(W_,49) = DYNTime;
InitialBoundSection
DYNX(W_,48) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getNextTimeEvent(\nprof.tab.tableID, \nprof.tab.timeScaled)")
  Modelica_Blocks_Tables_Internal_getNextTimeEvent_M(DymStruc0_construct(
  (Integer)(DYNX(W_,20))), DYNX(W_,49)));
PopModelContext();
InitialSection2
DYNX(W_,47) = IF Less(DYNX(W_,48),"prof.tab.nextTimeEventScaled", 1E+60,"1E+60",
   0) THEN DYNX(W_,48) ELSE 1E+60;
DYNX(X_,5) = DYNX(W_,27);
DYNX(X_,4) = DYNX(W_,26);
DYNX(X_,3) = DYNX(W_,25);
DYNX(X_,2) = DYNX(W_,24);
DYNX(X_,1) = DYNX(W_,23);
DYNX(X_,10) = DYNX(W_,29);
DYNX(X_,9) = DYNX(DP_,24);
DYNX(X_,8) = DYNX(DP_,23);
DYNX(X_,7) = DYNX(DP_,22);
DYNX(X_,6) = DYNX(W_,28);
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection
DYNX(Y_,0) = DYNTime;
DYNX(Y_,1) = DYNX(X_,10);
DYNX(Y_,2) = DYNX(X_,8);
DYNX(Y_,3) = DYNX(X_,9);
DYNX(Y_,4) = DYNX(X_,7);
DYNX(Y_,26) = DYNX(W_,35)*(DYNX(X_,10)-DYNX(DP_,29));
if (NewParameters_) {
DYNX(DYNhelp,16) = divinvGuarded(DYNX(W_,41),"reactor.tau_N2_hp");
}
DYNX(DYNhelp,17) = DYNX(W_,31)*DYNX(DP_,36);
DYNX(Y_,5) = DYNX(DYNhelp,16)*(DYNX(X_,9)-DYNX(X_,10))-divGuarded(DYNX(Y_,26),
  "reactor.Q_to_steam",DYNX(DYNhelp,17),"reactor.M_N2*reactor.cp_N2");
DYNX(W_,54) = DYNX(X_,0)*DYNX(DP_,20);
DYNX(DYNhelp,18) = DYNX(DP_,32)*DYNX(DP_,33);
if (NewParameters_) {
DYNX(DYNhelp,19) = divinvGuarded(DYNX(W_,37),"reactor.tau_g_f");
}
if (NewParameters_) {
DYNX(DYNhelp,20) = divinvGuarded(DYNX(W_,38),"reactor.tau_g_hp");
}
DYNX(Y_,6) = divGuarded((1.0-DYNX(DP_,21))*DYNX(W_,54),"(1.0-reactor.heat_f)*reactor.P",
  DYNX(DYNhelp,18),"reactor.M_g*reactor.cp_g")+DYNX(DYNhelp,19)*(DYNX(X_,7)-
  DYNX(X_,8))+DYNX(DYNhelp,20)*(DYNX(X_,9)-DYNX(X_,8));
if (NewParameters_) {
DYNX(DYNhelp,21) = divinvGuarded(DYNX(W_,39),"reactor.tau_hp_g");
}
if (NewParameters_) {
DYNX(DYNhelp,22) = divinvGuarded(DYNX(W_,40),"reactor.tau_hp_N2");
}
DYNX(Y_,7) = DYNX(DYNhelp,21)*(DYNX(X_,8)-DYNX(X_,9))+DYNX(DYNhelp,22)*(
  DYNX(X_,10)-DYNX(X_,9));
if (NewParameters_) {
DYNX(DYNhelp,23) = divinvGuarded(DYNX(W_,36),"reactor.tau_f_g");
}
DYNX(Y_,8) = DYNX(DP_,21)*DYNX(W_,54)*DYNX(W_,43)+DYNX(DYNhelp,23)*(DYNX(X_,8)-
  DYNX(X_,7));
DYNX(Y_,9) = DYNX(X_,1);
DYNX(Y_,10) = DYNX(X_,2);
DYNX(Y_,11) = DYNX(X_,3);
DYNX(Y_,12) = DYNX(X_,4);
DYNX(Y_,13) = DYNX(X_,5);
DYNX(Y_,14) = DYNX(X_,6);
DYNX(Y_,15) = DYNX(X_,0);
DYNX(W_,49) = DYNTime;
beginwhenBlock
whenModelica(GreaterEqualTimeMinor(PRE(DYNX(W_,47), 1), 0), 0) 
  DYNX(W_,48) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getNextTimeEvent(\nprof.tab.tableID, \nprof.tab.timeScaled)")
    Modelica_Blocks_Tables_Internal_getNextTimeEvent_M(DymStruc0_construct(
    (Integer)(DYNX(W_,20))), DYNX(W_,49)));
  PopModelContext();
endwhenModelica()
endwhenBlock



/* Introducing 1 common subexpressions whereof 1 are global used in 0
   expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,24) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValueNoDer2(\nprof.tab.tableID, \n1, \nprof.tab.timeScaled, \nprof.tab.nextTimeEventScaled, \npre(prof.tab.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValueNoDer2_M(DymStruc0_construct(
  (Integer)(DYNX(W_,20))), 1, DYNX(W_,49), DYNX(W_,48), PRE(DYNX(W_,48), 0)));
PopModelContext();
DYNX(Y_,18) = DYNX(W_,17)+DYNX(DYNhelp,24);

/* Introducing 1 common subexpressions whereof 1 are global used in 0
   expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,25) = cos(0.017453292519943295*DYNX(Y_,18));
DYNX(W_,51) = 0.5*DYNX(DP_,41)*DYNX(W_,44)*(1.0-DYNX(DYNhelp,25))-DYNX(W_,46);
DYNX(W_,52) = DYNX(DP_,39)*(DYNX(X_,7)-DYNX(DP_,22));
DYNX(W_,53) = DYNX(DP_,40)*(DYNX(X_,8)-DYNX(DP_,23));
DYNX(W_,50) = DYNX(W_,51)+DYNX(W_,52)+DYNX(W_,53);
if (NewParameters_) {
DYNX(DYNhelp,26) = divinvGuarded(DYNX(DP_,7),"reactor.Lambda");
}
DYNX(DYNhelp,27) = DYNX(DP_,8)*DYNX(X_,1)+DYNX(DP_,9)*DYNX(X_,2);
DYNX(DYNhelp,28) = DYNX(DP_,10)*DYNX(X_,3);
DYNX(Y_,16) = DYNX(DYNhelp,26)*(DYNX(W_,50)-DYNX(W_,22))*DYNX(X_,0)+
  DYNX(DYNhelp,27)+DYNX(DYNhelp,28)+DYNX(DP_,11)*DYNX(X_,4)+DYNX(DP_,12)*
  DYNX(X_,5)+DYNX(DP_,13)*DYNX(X_,6);
DYNX(Y_,17) = DYNX(W_,54)/(double)(1000000.0);

/* Introducing 1 common subexpressions whereof 1 are global used in 0
   expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,29) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValueNoDer2(\nprof.tab.tableID, \n2, \nprof.tab.timeScaled, \nprof.tab.nextTimeEventScaled, \npre(prof.tab.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValueNoDer2_M(DymStruc0_construct(
  (Integer)(DYNX(W_,20))), 2, DYNX(W_,49), DYNX(W_,48), PRE(DYNX(W_,48), 0)));
PopModelContext();
DYNX(Y_,19) = DYNX(W_,18)+DYNX(DYNhelp,29);

/* Introducing 1 common subexpressions whereof 1 are global used in 0
   expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,30) = (PushModelContext(1,"Modelica.Blocks.Tables.Internal.getTimeTableValueNoDer2(\nprof.tab.tableID, \n3, \nprof.tab.timeScaled, \nprof.tab.nextTimeEventScaled, \npre(prof.tab.nextTimeEventScaled))")
  Modelica_Blocks_Tables_Internal_getTimeTableValueNoDer2_M(DymStruc0_construct(
  (Integer)(DYNX(W_,20))), 3, DYNX(W_,49), DYNX(W_,48), PRE(DYNX(W_,48), 0)));
PopModelContext();
DYNX(Y_,20) = DYNX(W_,19)+DYNX(DYNhelp,30);
if (NewParameters_) {
DYNX(DYNhelp,31) = divinvGuarded(DYNX(W_,22),"reactor.beta");
}
DYNX(Y_,21) = DYNX(DYNhelp,31)*DYNX(W_,50);
DYNX(Y_,22) = DYNX(DYNhelp,31)*DYNX(W_,51);
DYNX(Y_,23) = DYNX(DYNhelp,31)*DYNX(W_,52);
DYNX(Y_,24) = DYNX(DYNhelp,31)*DYNX(W_,53);
if (NewParameters_) {
DYNX(DYNhelp,32) = divinvGuarded(DYNX(DP_,38),"reactor.delta_h");
}
DYNX(Y_,25) = DYNX(DYNhelp,32)*DYNX(Y_,26);

DynamicsSection
DYNX(F_,5) = DYNX(DYNhelp,26)*DYNX(DP_,18)*DYNX(X_,0)-DYNX(DP_,12)*DYNX(X_,5);
DYNX(F_,4) = DYNX(DYNhelp,26)*DYNX(DP_,17)*DYNX(X_,0)-DYNX(DP_,11)*DYNX(X_,4);
DYNX(F_,3) = DYNX(DYNhelp,26)*DYNX(DP_,16)*DYNX(X_,0)-DYNX(DP_,10)*DYNX(X_,3);
DYNX(F_,2) = DYNX(DYNhelp,26)*DYNX(DP_,15)*DYNX(X_,0)-DYNX(DP_,9)*DYNX(X_,2);
DYNX(F_,1) = DYNX(DYNhelp,26)*DYNX(DP_,14)*DYNX(X_,0)-DYNX(DP_,8)*DYNX(X_,1);
DYNX(F_,10) = DYNX(Y_,5);
DYNX(F_,9) = DYNX(Y_,7);
DYNX(F_,8) = DYNX(Y_,6);
DYNX(F_,7) = DYNX(Y_,8);
DYNX(F_,0) = DYNX(Y_,16);
DYNX(F_,6) = DYNX(DYNhelp,26)*DYNX(DP_,19)*DYNX(X_,0)-DYNX(DP_,13)*DYNX(X_,6);

AcceptedSection1
beginwhenBlock
whenModelica(GreaterEqualTimeMinor(PRE(DYNX(W_,47), 1), 0), 1) 
  DYNX(W_,47) = IF Less(DYNX(W_,48),"prof.tab.nextTimeEventScaled", 1E+60,
    "1E+60", 0) THEN DYNX(W_,48) ELSE 1E+60;
endwhenModelica()
endwhenBlock



AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include "dsblock6.c"

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("angleColumn", "[:#(type=Integer)]", 0, 2, 2.0,1.7976931348623157E+308,\
0.0,0,564)
DeclareParameter("velColumn", "[:#(type=Integer)]", 1, 3, 2.0,1.7976931348623157E+308,\
0.0,0,564)
DeclareParameter("accColumn", "[:#(type=Integer)]", 2, 4, 2.0,1.7976931348623157E+308,\
0.0,0,564)
DeclareVariable("prof.angleColumn", "Column index for angle [:#(type=Integer)]",\
 0, 2, 2.0,1.7976931348623157E+308,0.0,0,517)
DeclareVariable("prof.velColumn", "[:#(type=Integer)]", 1, 2, 2.0,\
1.7976931348623157E+308,0.0,0,517)
DeclareVariable("prof.accColumn", "[:#(type=Integer)]", 2, 2, 2.0,\
1.7976931348623157E+308,0.0,0,517)
DeclareAlias2("prof.angleDeg", "Drum angle [deg] []", "drumAngleDeg", 1, 3, 18, 0)
DeclareAlias2("prof.velDeg_s", "Drum velocity [deg/s] []", "drumVelDeg_s", 1, 3,\
 19, 0)
DeclareAlias2("prof.accDeg_s2", "Drum acceleration [deg/s2] []", "drumAccDeg_s2", 1,\
 3, 20, 0)
DeclareVariable("prof.tab.nout", "Number of outputs [:#(type=Integer)]", 3, 3, \
1.0,1.7976931348623157E+308,0.0,0,2565)
DeclareAlias2("prof.tab.y[1]", "Connector of Real output signals", \
"drumAngleDeg", 1, 3, 18, 1024)
DeclareAlias2("prof.tab.y[2]", "Connector of Real output signals", \
"drumVelDeg_s", 1, 3, 19, 1024)
DeclareAlias2("prof.tab.y[3]", "Connector of Real output signals", \
"drumAccDeg_s2", 1, 3, 20, 1024)
DeclareVariable("prof.tab.tableOnFile", "= true, if table is defined on file or in function usertab [:#(type=Boolean)]",\
 4, true, 0.0,0.0,0.0,0,2563)
DeclareParameter("prof.tab.verboseRead", "= true, if info message that file is loading is to be printed [:#(type=Boolean)]",\
 3, true, 0.0,0.0,0.0,0,2610)
DeclareVariable("prof.tab.columns[1]", "Columns of table to be interpolated [:#(type=Integer)]",\
 5, 0, 0.0,0.0,0.0,0,2565)
DeclareVariable("prof.tab.columns[2]", "Columns of table to be interpolated [:#(type=Integer)]",\
 6, 0, 0.0,0.0,0.0,0,2565)
DeclareVariable("prof.tab.columns[3]", "Columns of table to be interpolated [:#(type=Integer)]",\
 7, 0, 0.0,0.0,0.0,0,2565)
DeclareVariable("prof.tab.smoothness", "Smoothness of table interpolation [:#(type=Modelica.Blocks.Types.Smoothness)]",\
 8, 1, 1.0,6.0,0.0,0,2565)
DeclareVariable("prof.tab.extrapolation", "Extrapolation of data outside the definition range [:#(type=Modelica.Blocks.Types.Extrapolation)]",\
 9, 1, 1.0,4.0,0.0,0,2565)
DeclareVariable("prof.tab.timeScale", "Time scale of first table column [s]", 10,\
 1, 1E-15,1.7976931348623157E+308,0.0,0,2561)
DeclareParameter("prof.tab.offset[1]", "Offsets of output signals", 4, 0, \
0.0,0.0,0.0,0,2608)
DeclareParameter("prof.tab.startTime", "Output = offset for time < startTime [s]",\
 5, 0, 0.0,0.0,0.0,0,2608)
DeclareVariable("prof.tab.shiftTime", "Shift time of first table column [s]", 11,\
 0.0, 0.0,0.0,0.0,0,2561)
DeclareParameter("prof.tab.timeEvents", "Time event handling of table interpolation [:#(type=Modelica.Blocks.Types.TimeEvents)]",\
 6, 1, 1.0,3.0,0.0,0,2612)
DeclareVariable("prof.tab.verboseExtrapolation", "= true, if warning messages are to be printed if time is outside the table definition range [:#(type=Boolean)]",\
 12, false, 0.0,0.0,0.0,0,2563)
DeclareVariable("prof.tab.t_min", "Minimum abscissa value defined in table [s]",\
 13, 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("prof.tab.t_max", "Maximum abscissa value defined in table [s]",\
 14, 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("prof.tab.t_minScaled", "Minimum (scaled) abscissa value defined in table [1]",\
 15, 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("prof.tab.t_maxScaled", "Maximum (scaled) abscissa value defined in table [1]",\
 16, 0.0, 0.0,0.0,0.0,0,2561)
DeclareVariable("prof.tab.p_offset[1]", "Offsets of output signals", 17, 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("prof.tab.p_offset[2]", "Offsets of output signals", 18, 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("prof.tab.p_offset[3]", "Offsets of output signals", 19, 0.0, \
0.0,0.0,0.0,0,2561)
DeclareVariable("prof.tab.tableID.id", "[:#(type=Integer)]", 20, 0, 0.0,0.0,0.0,\
0,2565)
DeclareVariable("prof.tab.nextTimeEvent", "Next time event instant [s]", 47, 0, \
0.0,0.0,0.0,0,2704)
DeclareVariable("prof.tab.nextTimeEventScaled", "Next scaled time event instant [1]",\
 48, 0, 0.0,0.0,0.0,0,2704)
DeclareVariable("prof.tab.timeScaled", "Scaled time [1]", 49, 0.0, 0.0,0.0,0.0,0,2560)
DeclareParameter("reactor.Lambda", "Prompt neutron generation time [s] []", 7, \
0.000195734, 0.0,0.0,0.0,0,560)
DeclareVariable("reactor.nGroups", "[:#(type=Integer)]", 21, 6, 0.0,0.0,0.0,0,517)
DeclareParameter("reactor.lambdas[1]", "Delayed group decay constants [1/s] []",\
 8, 0.01334, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.lambdas[2]", "Delayed group decay constants [1/s] []",\
 9, 0.03274, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.lambdas[3]", "Delayed group decay constants [1/s] []",\
 10, 0.1208, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.lambdas[4]", "Delayed group decay constants [1/s] []",\
 11, 0.3028, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.lambdas[5]", "Delayed group decay constants [1/s] []",\
 12, 0.8495, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.lambdas[6]", "Delayed group decay constants [1/s] []",\
 13, 2.853, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.betas[1]", "Delayed group fractions", 14, 0.000290591,\
 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.betas[2]", "Delayed group fractions", 15, 0.00112869, \
0.0,0.0,0.0,0,560)
DeclareParameter("reactor.betas[3]", "Delayed group fractions", 16, 0.00116402, \
0.0,0.0,0.0,0,560)
DeclareParameter("reactor.betas[4]", "Delayed group fractions", 17, 0.00269454, \
0.0,0.0,0.0,0,560)
DeclareParameter("reactor.betas[5]", "Delayed group fractions", 18, 0.000920043,\
 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.betas[6]", "Delayed group fractions", 19, 0.000441185,\
 0.0,0.0,0.0,0,560)
DeclareVariable("reactor.beta", "Total delayed neutron fraction", 22, 0.0, \
0.0,0.0,0.0,0,513)
DeclareVariable("reactor.C_ss[1]", "", 23, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.C_ss[2]", "", 24, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.C_ss[3]", "", 25, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.C_ss[4]", "", 26, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.C_ss[5]", "", 27, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.C_ss[6]", "", 28, 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("reactor.P_r", "Rated thermal power [W] [W]", 20, 6000000.0, \
0.0,0.0,0.0,0,560)
DeclareParameter("reactor.heat_f", "Fraction of power deposited in fuel [1]", 21,\
 0.9, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.Tf0", "[K|degC]", 22, 1173.15, 0.0,1.7976931348623157E+308,\
300.0,0,560)
DeclareParameter("reactor.Tm0", "[K|degC]", 23, 1150.15, 0.0,1.7976931348623157E+308,\
300.0,0,560)
DeclareParameter("reactor.Thp0", "[K|degC]", 24, 1073.15, 0.0,1.7976931348623157E+308,\
300.0,0,560)
DeclareParameter("reactor.TN_in", "[K|degC]", 25, 683.15, 0.0,1.7976931348623157E+308,\
300.0,0,560)
DeclareParameter("reactor.TN_out", "[K|degC]", 26, 1073.15, 0.0,1.7976931348623157E+308,\
300.0,0,560)
DeclareVariable("reactor.TN0", "[K|degC]", 29, 288.15, 0.0,1.7976931348623157E+308,\
300.0,0,513)
DeclareParameter("reactor.Tsg0", "[K|degC]", 27, 505.15, 0.0,1.7976931348623157E+308,\
300.0,0,560)
DeclareParameter("reactor.T_fw_in", "[K|degC]", 28, 471.45, 0.0,1.7976931348623157E+308,\
300.0,0,560)
DeclareParameter("reactor.T_steam_out", "[K|degC]", 29, 505.15, 0.0,\
1.7976931348623157E+308,300.0,0,560)
DeclareParameter("reactor.M_f", "[kg]", 30, 4355.259, 0.0,1.7976931348623157E+308,\
0.0,0,560)
DeclareParameter("reactor.cp_f", "[J/(kg.K)]", 31, 748.72, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.M_g", "[kg]", 32, 673.921, 0.0,1.7976931348623157E+308,\
0.0,0,560)
DeclareParameter("reactor.cp_g", "[J/(kg.K)]", 33, 1850.0, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.M_hp", "[kg]", 34, 119.678, 0.0,1.7976931348623157E+308,\
0.0,0,560)
DeclareParameter("reactor.cp_hp", "[J/(kg.K)]", 35, 771.3, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.cp_N2", "[J/(kg.K)]", 36, 1182.0, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.tau_N", "[s]", 37, 5.0, 0.0,0.0,0.0,0,560)
DeclareVariable("reactor.m_dot_N", "[kg/s]", 30, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.M_N2", "[kg]", 31, 0.0, 0.0,1.7976931348623157E+308,0.0,\
0,513)
DeclareParameter("reactor.delta_h", "J/kg [m2/s2]", 38, 2035870.0, 0.0,0.0,0.0,0,560)
DeclareVariable("reactor.G_f_g", "[W/K]", 32, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.G_g_hp", "[W/K]", 33, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.G_hp_N2", "[W/K]", 34, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.G_N2_sg", "[W/K]", 35, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.tau_f_g", "[s]", 36, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.tau_g_f", "[s]", 37, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.tau_g_hp", "[s]", 38, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.tau_hp_g", "[s]", 39, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.tau_hp_N2", "[s]", 40, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.tau_N2_hp", "[s]", 41, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.tau_N2_sg", "[s]", 42, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.inv_Mf_cp_f", "[m-2.kg-1.s2.K]", 43, 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("reactor.alpha_f", "Fuel feedback [\316\224k/k per K] []", 39, \
-4.59E-05, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.alpha_m", "Moderator feedback [\316\224k/k per K] []",\
 40, -2.21E-05, 0.0,0.0,0.0,0,560)
DeclareParameter("reactor.n_drums", "[:#(type=Integer)]", 41, 12, 0.0,0.0,0.0,0,564)
DeclareParameter("reactor.rho_max_total_pcm", "", 42, -13174, 0.0,0.0,0.0,0,560)
DeclareVariable("reactor.rho_max_per_drum", "", 44, 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("reactor.u0", "Steady-state drum angle [deg] []", 43, 45.0, \
0.0,0.0,0.0,0,560)
DeclareVariable("reactor.rho_ss_single", "", 45, 0.0, 0.0,0.0,0.0,0,513)
DeclareVariable("reactor.rho_ss_total", "", 46, 0.0, 0.0,0.0,0.0,0,513)
DeclareAlias2("reactor.drumAngleDeg", "Angle applied to all drums [deg] []", \
"drumAngleDeg", 1, 3, 18, 0)
DeclareState("reactor.n", "Normalized power [1]", 0, 1.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("reactor.der(n)", "der(Normalized power) [s-1]", 0, 0.0, \
0.0,0.0,0.0,0,512)
DeclareState("reactor.c[1]", "Delayed precursors", 1, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("reactor.der(c[1])", "der(Delayed precursors)", 1, 0.0, \
0.0,0.0,0.0,0,512)
DeclareState("reactor.c[2]", "Delayed precursors", 2, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("reactor.der(c[2])", "der(Delayed precursors)", 2, 0.0, \
0.0,0.0,0.0,0,512)
DeclareState("reactor.c[3]", "Delayed precursors", 3, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("reactor.der(c[3])", "der(Delayed precursors)", 3, 0.0, \
0.0,0.0,0.0,0,512)
DeclareState("reactor.c[4]", "Delayed precursors", 4, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("reactor.der(c[4])", "der(Delayed precursors)", 4, 0.0, \
0.0,0.0,0.0,0,512)
DeclareState("reactor.c[5]", "Delayed precursors", 5, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("reactor.der(c[5])", "der(Delayed precursors)", 5, 0.0, \
0.0,0.0,0.0,0,512)
DeclareState("reactor.c[6]", "Delayed precursors", 6, 0.0, 0.0,0.0,0.0,0,544)
DeclareDerivative("reactor.der(c[6])", "der(Delayed precursors)", 6, 0.0, \
0.0,0.0,0.0,0,512)
DeclareState("reactor.Tf", "[K|degC]", 7, 0.0, 0.0,1.7976931348623157E+308,300.0,\
0,544)
DeclareDerivative("reactor.der(Tf)", "[K/s]", 7, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("reactor.Tm", "[K|degC]", 8, 0.0, 0.0,1.7976931348623157E+308,300.0,\
0,544)
DeclareDerivative("reactor.der(Tm)", "[K/s]", 8, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("reactor.Thp", "[K|degC]", 9, 0.0, 0.0,1.7976931348623157E+308,\
300.0,0,544)
DeclareDerivative("reactor.der(Thp)", "[K/s]", 9, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("reactor.TN2", "[K|degC]", 10, 0.0, 0.0,1.7976931348623157E+308,\
300.0,0,544)
DeclareDerivative("reactor.der(TN2)", "[K/s]", 10, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("reactor.rho", "Reactivity [\316\224k/k] []", 50, 0.0, 0.0,0.0,\
0.0,0,512)
DeclareVariable("reactor.rho_drums", "Drum reactivity contribution [\316\224k/k] []",\
 51, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("reactor.rho_fuel", "Fuel temperature reactivity contribution [\316\224k/k] []",\
 52, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("reactor.rho_moderator", "Moderator temperature reactivity contribution [\316\224k/k] []",\
 53, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("reactor.rho_dollars", "Reactivity [$] []", "rho_dollars", 1, 3, 21,\
 0)
DeclareAlias2("reactor.rho_drums_dollars", "Drum reactivity contribution [$] []",\
 "rho_drums_dollars", 1, 3, 22, 0)
DeclareAlias2("reactor.rho_fuel_dollars", "Fuel reactivity contribution [$] []",\
 "rho_fuel_dollars", 1, 3, 23, 0)
DeclareAlias2("reactor.rho_moderator_dollars", "Moderator reactivity contribution [$] []",\
 "rho_moderator_dollars", 1, 3, 24, 0)
DeclareVariable("reactor.P", "Thermal power [W] [W]", 54, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("reactor.P_MW", "Thermal power [MW] []", "P_MW", 1, 3, 17, 0)
DeclareAlias2("reactor.Q_to_steam", "Heat available to generate 232C steam [W] [W]",\
 "Q_to_steam", 1, 3, 26, 0)
DeclareAlias2("reactor.m_dot_steam", "Steam production rate [kg/s] [kg/s]", \
"m_dot_steam", 1, 3, 25, 0)
DeclareOutput("t", "Time [s] [s]", 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("TN2", "Reactor N2 node temperature [K] [K|degC]", 1, 0.0, 0.0,\
1.7976931348623157E+308,300.0,0,512)
DeclareOutput("Tm", "Moderator/graphite temperature [K] [K|degC]", 2, 0.0, 0.0,\
1.7976931348623157E+308,300.0,0,512)
DeclareOutput("Thp", "Heat-pipe node temperature [K] [K|degC]", 3, 0.0, 0.0,\
1.7976931348623157E+308,300.0,0,512)
DeclareOutput("Tf", "Fuel temperature [K] [K|degC]", 4, 0.0, 0.0,\
1.7976931348623157E+308,300.0,0,512)
DeclareOutput("dTN2", "d(TN2)/dt [K/s] [K/s]", 5, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("dTm", "d(Tm)/dt [K/s] [K/s]", 6, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("dThp", "d(Thp)/dt [K/s] [K/s]", 7, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("dTf", "d(Tf)/dt [K/s] [K/s]", 8, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("c[1]", "Delayed neutron precursor states c[1..6] []", 9, 0.0, \
0.0,0.0,0.0,0,512)
DeclareOutput("c[2]", "Delayed neutron precursor states c[1..6] []", 10, 0.0, \
0.0,0.0,0.0,0,512)
DeclareOutput("c[3]", "Delayed neutron precursor states c[1..6] []", 11, 0.0, \
0.0,0.0,0.0,0,512)
DeclareOutput("c[4]", "Delayed neutron precursor states c[1..6] []", 12, 0.0, \
0.0,0.0,0.0,0,512)
DeclareOutput("c[5]", "Delayed neutron precursor states c[1..6] []", 13, 0.0, \
0.0,0.0,0.0,0,512)
DeclareOutput("c[6]", "Delayed neutron precursor states c[1..6] []", 14, 0.0, \
0.0,0.0,0.0,0,512)
DeclareOutput("n", "Normalized power [1]", 15, 1.0, 0.0,0.0,0.0,0,512)
DeclareOutput("dn", "d(n)/dt [1/s] [s-1]", 16, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("P_MW", "Thermal power [MW] []", 17, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("drumAngleDeg", "Applied drum angle [deg] []", 18, 0.0, 0.0,0.0,\
0.0,0,512)
DeclareOutput("drumVelDeg_s", "Drum velocity [deg/s] []", 19, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("drumAccDeg_s2", "Drum acceleration [deg/s2] []", 20, 0.0, \
0.0,0.0,0.0,0,512)
DeclareOutput("rho_dollars", "Reactivity [$] []", 21, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("rho_drums_dollars", "Drum reactivity contribution [$] []", 22, \
0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("rho_fuel_dollars", "Fuel reactivity contribution [$] []", 23, 0.0,\
 0.0,0.0,0.0,0,512)
DeclareOutput("rho_moderator_dollars", "Moderator reactivity contribution [$] []",\
 24, 0.0, 0.0,0.0,0.0,0,512)
DeclareOutput("m_dot_steam", "Steam production rate [kg/s] [kg/s]", 25, 0.0, \
0.0,0.0,0.0,0,512)
DeclareOutput("Q_to_steam", "Heat available to steam [W] [W]", 26, 0.0, 0.0,0.0,\
0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartPreBlock
pre(DYNX(W_,47),"prof.tab.nextTimeEvent", 0, 1);
preD(DYNX(W_,48),"prof.tab.nextTimeEventScaled", 0, 0);
EndPreBlock
UpdateQEvaluate(2)
EndDataBlock
